const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){
 let token='A',reads=0,writes=0,callback;const pending=[];
 const raw={auth:{getSession:async()=>({data:{session:{user:{id:token},access_token:token}},error:null}),onAuthStateChange:fn=>{callback=fn}},functions:{invoke:async()=>{writes++;return {data:{ok:true}}}},from(table){let op='read';const result={data:[{table,token}],error:null};const b={select(){return b},eq(){return b},in(){return b},range(){return b},order(){return b},single(){return b},abortSignal(){return b},insert(){op='write';return b},update(){op='write';return b},delete(){op='write';return b},then(resolve,reject){return new Promise(r=>{op==='read'?reads++:writes++;pending.push(()=>r(result))}).then(resolve,reject)}};return b}};
 const context={window:{sessionStorage:{},supabase:{createClient:()=>raw}},structuredClone,Promise,Map,Proxy};vm.runInNewContext(fs.readFileSync('foundation/backend.js','utf8'),context);const client=context.window.SiKoyekBackend.getClient('https://fixture.invalid','publishable');
 return {client,raw,backend:context.window.SiKoyekBackend,counts:()=>({reads,writes}),flush(){pending.splice(0).forEach(fn=>fn())},auth(next){token=next;callback('SIGNED_IN',{user:{id:next},access_token:next})}};
}
const tick=()=>new Promise(r=>setImmediate(r));
test('identical concurrent reads share one operation and each gets independent data',async()=>{const s=setup(),a=Promise.resolve(s.client.from('projects').select('*').eq('id','p1')),b=Promise.resolve(s.client.from('projects').select('*').eq('id','p1'));await tick();assert.equal(s.counts().reads,1);s.flush();const [x,y]=await Promise.all([a,b]);x.data[0].table='changed';assert.equal(y.data[0].table,'projects');const next=Promise.resolve(s.client.from('projects').select('*').eq('id','p1'));await tick();assert.equal(s.counts().reads,2);s.flush();await next});
test('filters and auth changes cannot share a read',async()=>{const s=setup(),a=Promise.resolve(s.client.from('projects').select('*').eq('id','p1'));await tick();s.auth('B');const b=Promise.resolve(s.client.from('projects').select('*').eq('id','p1')),c=Promise.resolve(s.client.from('projects').select('*').eq('id','p2'));await tick();assert.equal(s.counts().reads,3);s.flush();const [x,y]=await Promise.all([a,b,c]);assert.equal(x.data[0].token,'A');assert.equal(y.data[0].token,'B')});
test('writes execute separately; invocation invalidates pending reads',async()=>{const s=setup(),a=Promise.resolve(s.client.from('projects').insert({id:'p1'})),b=Promise.resolve(s.client.from('projects').insert({id:'p1'}));await tick();assert.equal(s.counts().writes,2);s.flush();await Promise.all([a,b]);const read=Promise.resolve(s.client.from('projects').select('*'));await tick();await s.client.functions.invoke('user-management',{body:{action:'update'}});const second=Promise.resolve(s.client.from('projects').select('*'));await tick();assert.equal(s.counts().reads,2);s.flush();await Promise.all([read,second]);assert.equal(s.counts().writes,3)});
test('abort signals use independent reads',async()=>{const s=setup(),signal=new AbortController().signal,a=Promise.resolve(s.client.from('projects').select('*').abortSignal(signal)),b=Promise.resolve(s.client.from('projects').select('*').abortSignal(signal));await tick();assert.equal(s.counts().reads,2);s.flush();await Promise.all([a,b])});
test('backend selection is fixed after initialization',()=>{const s=setup();assert.throws(()=>s.backend.registerBackend(()=>{}),/initialized/);assert.equal(s.backend.getClient('https://fixture.invalid','publishable'),s.client)});
test('configured client resolves the tenant and rejects explicit access to another backend',()=>{
 let captured;const raw={auth:{onAuthStateChange(){}},from(){}};
 const config={url:'https://tenant-fixture.supabase.co',key:'sb_publishable_fixture',storageKey:'sb-tenant-fixture-auth-token'};
 const window={SiKoyekConfig:config,sessionStorage:{},supabase:{createClient(...args){captured=args;return raw}}};
 vm.runInNewContext(fs.readFileSync('foundation/backend.js','utf8'),{window,structuredClone});
 window.SiKoyekBackend.getClient();assert.equal(captured[0],config.url);assert.equal(captured[1],config.key);assert.equal(captured[2].auth.storageKey,config.storageKey);assert.equal(captured[2].auth.storage,window.sessionStorage);
 assert.throws(()=>window.SiKoyekBackend.getClient('https://different.supabase.co',config.key),/lingkungan aktif/);
});
