const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright');
const roots={before:path.resolve(process.argv[2]),after:path.resolve(process.argv[3]||'.')};const fixture=fs.readFileSync(path.join(__dirname,'fixture.js'),'utf8');
(async()=>{
 const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local'),parts=url.pathname.split('/').filter(Boolean),which=parts.shift(),root=roots[which];if(!root){res.writeHead(404);return res.end()}const file=path.join(root,parts.join('/')||'index.html');if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file))}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const browser=await chromium.launch({...(process.env.SIKOYEK_CHROMIUM ? {executablePath:process.env.SIKOYEK_CHROMIUM} : {}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const snapshots={};
 for(const which of ['before','after']){const context=await browser.newContext();await context.addInitScript(fixture);await context.route('**/*',route=>{if(route.request().url().startsWith('http://127.0.0.1:'))return route.continue();if(route.request().url().includes('cdn.jsdelivr.net/npm/@supabase/supabase-js'))return route.fulfill({contentType:'text/javascript',body:'/* local fixture */'});return route.abort()});const page=await context.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/'+which+'/index.html');await page.waitForTimeout(3500);snapshots[which]=await page.evaluate(()=>Object.fromEntries(Object.getOwnPropertyNames(window).filter(k=>/^(?:save|p5Save|p5Delete|mdSave|mdConfirm|confirmDel|umSave|umDelete|login$|logout$|forgotPassword$)/i.test(k)).filter(k=>typeof window[k]==='function'&&!String(window[k]).includes('[native code]')).sort().map(k=>[k,String(window[k])])));await context.close()}
 await browser.close();server.close();assert.deepEqual(snapshots.after,snapshots.before,'Active write/auth handlers must preserve their complete implementation');const result={passed:true,handlers:Object.keys(snapshots.after).length,hashes:Object.fromEntries(Object.entries(snapshots.after).map(([name,source])=>[name,crypto.createHash('sha256').update(source).digest('hex')]))};fs.writeFileSync('docs/cloud-audit/business-handlers.json',JSON.stringify(result,null,2));console.log('PASS: '+result.handlers+' active CRUD/auth handler implementations unchanged');
})().catch(error=>{console.error(error);process.exit(1)});
