(() => {
const role=window.__testRole||'admin', uid='00000000-0000-4000-8000-000000000001';
const user={id:uid,email:'audit@example.invalid',user_metadata:{full_name:'Pengguna Uji'}};
const summary=Array.from({length:6},(_,i)=>({project_id:'p'+i,project_code:'P26'+String(i+1).padStart(3,'0'),project_name:'Proyek Uji '+(i+1),contract_value:100000000+i*10000000,total_rap:80000000,project_progress:20+i*10,cost_ratio:10+i*12,rap_consumption:15+i*15,health_status:i<2?'SEHAT':i<4?'WASPADA':'BERISIKO',estimated_profit:20000000,cash_in:50000000,cash_out:30000000,net_cashflow:20000000,project_date:'2026-09-01',start_date:'2026-09-01',end_date:'2026-12-31',status:'JALAN'}));
const modules=['DASHBOARD','PROJECTS','MASTER_DATA','PROGRESS','RAP','KEUANGAN','USERS','LAPORAN'];
const permissions=modules.flatMap(m=>['VIEW','ADD','EDIT','DELETE'].map(a=>({id:m+'_'+a,module:m,action:a,name:m+' '+a})));
const allowed=permissions.filter(p=>role==='admin'||!['USERS','MASTER_DATA'].includes(p.module)&& (role==='direktur'||p.action==='VIEW'));
const tables={project_summary:summary,projects:summary.map(p=>({...p,id:p.project_id,owner_name:'Pemilik Uji',location:'Tasikmalaya',category:'Perumahan',project_manager:'Mandor Uji'})),profiles:[{id:uid,full_name:'Pengguna Uji',email:user.email,is_active:true,role_id:role,roles:{name:role,description:role},created_at:'2026-01-01'}],roles:['admin','direktur','keuangan','marketing','pelaksana'].map(name=>({id:name,name,is_active:true})),permissions,role_permissions:allowed.map(p=>({role_id:role,permission_id:p.id})),project_work_items:summary.flatMap(p=>[{id:p.project_id+'i1',project_id:p.project_id,work_name:'Pondasi',weight:0.4,sort_order:1},{id:p.project_id+'i2',project_id:p.project_id,work_name:'Dinding',weight:0.6,sort_order:2}]),project_rap:summary.map(p=>({project_id:p.project_id,material:30000000,labor:20000000,equipment:10000000,operational:10000000,subcontract:5000000,other:5000000})),progress_records:summary.map(p=>({id:p.project_id+'pr',project_id:p.project_id,work_item_id:p.project_id+'i1',progress_date:'2026-10-01',progress_percentage:0.5,notes:'Uji'})),financial_transactions:summary.flatMap(p=>[{id:p.project_id+'t1',project_id:p.project_id,transaction_date:'2026-10-01',transaction_type:'MASUK',category:'Uang Muka',amount:50000000,description:'Uji masuk',payment_method:'Transfer'},{id:p.project_id+'t2',project_id:p.project_id,transaction_date:'2026-10-02',transaction_type:'KELUAR',category:'Material',amount:30000000,description:'Uji keluar',payment_method:'Cash'}]),project_categories:[{id:'c1',name:'Perumahan',is_active:true,sort_order:1}],project_managers:[{id:'m1',name:'Mandor Uji',is_active:true,sort_order:1}],transaction_categories:[{id:'tc1',name:'Material',transaction_type:'KELUAR',is_active:true,sort_order:1}],payment_methods:[{id:'pm1',name:'Transfer',is_active:true,sort_order:1}]};
window.__audit={clients:0,queries:[],writes:[],observers:0,callbacks:0,intervals:[],errors:[]};
const native=window.MutationObserver;window.MutationObserver=class extends native{constructor(cb){window.__audit.observers++;super((...args)=>{window.__audit.callbacks++;cb(...args)})}};
const interval=window.setInterval;window.setInterval=(cb,ms,...args)=>{window.__audit.intervals.push(ms);return interval(cb,ms,...args)};
function builder(table){const spec={table,op:'select',cols:'*',filters:[],order:[],single:false,head:false};let task;const b={select(cols='*',options={}){spec.cols=cols;spec.head=options.head;return b},eq(k,v){spec.filters.push(['eq',k,v]);return b},in(k,v){spec.filters.push(['in',k,v]);return b},gte(k,v){spec.filters.push(['gte',k,v]);return b},lte(k,v){spec.filters.push(['lte',k,v]);return b},order(k,o){spec.order.push([k,o]);return b},limit(){return b},range(){return b},single(){spec.single=true;return b},maybeSingle(){spec.single=true;return b},insert(v){spec.op='insert';spec.value=v;return b},update(v){spec.op='update';spec.value=v;return b},upsert(v){spec.op='upsert';spec.value=v;return b},delete(){spec.op='delete';return b},then(resolve,reject){if(!task)task=new Promise(r=>{window.__audit.queries.push(JSON.parse(JSON.stringify(spec)));if(spec.op!=='select')window.__audit.writes.push(spec);setTimeout(()=>{let rows=structuredClone(tables[table]||[]);for(const [op,k,v] of spec.filters)rows=rows.filter(x=>op==='eq'?x[k]===v:op==='in'?v.includes(x[k]):op==='gte'?x[k]>=v:x[k]<=v);r({data:spec.head?null:spec.single?(rows[0]||null):rows,error:null,count:rows.length})},20)});return task.then(resolve,reject)}};return b}
window.supabase={createClient(){window.__audit.clients++;return {from:builder,auth:{getSession:async()=>({data:{session:window.__testLoggedOut?null:{user,access_token:'fixture-token'}},error:null}),getUser:async()=>({data:{user},error:null}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signOut:async()=>({error:null}),signInWithPassword:async()=>({data:{user},error:null})},functions:{invoke:async(name,opts)=>{window.__audit.writes.push({name,opts});return {data:{success:true},error:null}}}}}};
})();
