const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(process.argv[2]),output=path.resolve(process.argv[3]||'docs/cloud-audit/preview-browser.json');
(async()=>{
 const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://local').pathname);if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end('missing')}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file))}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const browser=await chromium.launch({...(process.env.SIKOYEK_CHROMIUM?{executablePath:process.env.SIKOYEK_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const origin='http://127.0.0.1:'+server.address().port,errors=[],external=[],missing=[],checks=[];
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.setDefaultTimeout(15000);
 await context.route('**/*',route=>{if(route.request().url().startsWith(origin+'/'))return route.continue();external.push(route.request().url());return route.abort()});
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()===404)missing.push(r.url())});
 const check=name=>{checks.push(name);console.log('PASS '+name)};
 const enter=async(tenant,role='admin')=>{await page.goto(origin+'/');await page.selectOption('#tenant',tenant);await page.selectOption('#role',role);await page.click('#open');await page.waitForSelector('.dashboard-head');await page.waitForTimeout(800);};
 const rows=table=>page.evaluate(async table=>(await sb.from(table).select('*')).data,table);
 try{
  await enter('master');assert.equal((await rows('projects')).length,6);check('master seeded dashboard');
  await page.evaluate(()=>openProjectForm());await page.waitForSelector('#uiFinalNext');await page.click('#uiFinalNext');assert.equal((await rows('projects')).length,6);check('required validation does not save');
  await page.fill('#f_code','PREVIEW-001');await page.fill('#f_name','Proyek Uji Tambah');await page.fill('#f_contract','100000000');await page.click('#uiFinalNext');assert.equal((await rows('projects')).length,6);check('confirmation does not save until final click');await page.click('#uiFinalSave');await page.waitForSelector('#modal',{state:'detached'});
  const id=(await rows('projects')).find(p=>p.project_code==='PREVIEW-001').id;await page.evaluate(id=>openProject(id),id);await page.waitForFunction(()=>state.detail?.project?.project_code==='PREVIEW-001');assert.equal((await rows('projects')).length,7);check('project create through UI persists');
  await page.evaluate(id=>p5EditProject(id),id);await page.waitForSelector('#p5_name');await page.fill('#p5_name','Proyek Uji Edit');await page.click('#p5EditSave');assert.equal((await rows('projects')).find(p=>p.id===id).project_name,'Proyek Uji Edit');check('unstarted project edit through UI');
  await page.evaluate(()=>openItemForm());await page.waitForSelector('#wi_name');await page.fill('#wi_name','Pekerjaan Uji');await page.fill('#wi_weight','40');await page.evaluate(()=>saveItem());assert.equal((await rows('project_work_items')).filter(i=>i.project_id===id).length,1);check('work item create through UI');
  await page.evaluate(()=>openRapForm());await page.waitForSelector('#rap_material');await page.fill('#rap_material','30000000');await page.evaluate(()=>saveRap());assert.equal((await rows('project_rap')).find(r=>r.project_id===id).material,30000000);check('RAP save through UI');
  await page.evaluate(()=>openProgressForm());await page.waitForSelector('#pr_pct');await page.fill('#pr_pct','25');await page.evaluate(()=>saveProgress());assert.equal((await rows('progress_records')).filter(p=>p.project_id===id).length,1);assert.equal((await rows('projects')).find(p=>p.id===id).project_progress,10);check('progress save and weighted contribution');
  await page.evaluate(()=>openTxForm());await page.waitForSelector('#tx_amount');await page.selectOption('#tx_type','KELUAR');await page.waitForSelector('#tx_cat option[value="Material"]',{state:'attached'});await page.selectOption('#tx_cat','Material');await page.fill('#tx_amount','12345');await page.fill('#tx_desc','Transaksi Uji');await page.evaluate(()=>saveTx());assert.equal((await rows('financial_transactions')).filter(t=>t.project_id===id).length,1);check('financial transaction save through UI');
  await page.reload();await page.waitForSelector('.dashboard-head');assert.equal((await rows('projects')).length,7);check('preview mutations survive reload');
  await page.evaluate(id=>openProject(id),id);await page.waitForTimeout(800);assert.equal(await page.getByRole('button',{name:'Edit Proyek',exact:true}).isDisabled(),true);check('project lock after financial history');
  await page.evaluate(()=>go('users'));await page.waitForSelector('.um-grid');await page.evaluate(()=>umAdd());await page.fill('#um_name','User Baru Uji');await page.fill('#um_email','baru@preview.invalid');await page.fill('#um_password','Preview999!');await page.fill('#um_password_confirm','Preview999!');await page.selectOption('#um_role','keuangan');await page.evaluate(()=>umSaveAdd());assert.ok((await rows('profiles')).some(p=>p.email==='baru@preview.invalid'));check('user create invokes isolated preview adapter');
  const newUser=(await rows('profiles')).find(p=>p.email==='baru@preview.invalid');await page.evaluate(id=>umEdit(id),newUser.id);await page.fill('#um_edit_name','User Edit Uji');await page.evaluate(id=>umSaveEdit(id),newUser.id);assert.equal((await rows('profiles')).find(p=>p.id===newUser.id).full_name,'User Edit Uji');check('user edit');
  page.once('dialog',dialog=>dialog.accept());await page.evaluate(id=>umDelete(id,'User Edit Uji'),newUser.id);assert.equal((await rows('profiles')).some(p=>p.id===newUser.id),false);check('user delete confirmation');
  await page.evaluate(()=>go('master-data'));await page.waitForSelector('.md-page');
  for(const [opener,table,name] of [['mdAddFinanceCategory','transaction_categories','Kategori Uji Simpan'],['mdAddPaymentMethod','payment_methods','Metode Uji Simpan']]){
   await page.evaluate(fn=>window[fn](),opener);await page.fill('#md_name','');await page.locator('#modal').getByRole('button',{name:'Simpan',exact:true}).click();assert.ok(await page.locator('#md_name').isVisible());
   await page.fill('#md_name',name);await page.locator('#modal').getByRole('button',{name:'Simpan',exact:true}).click();await page.waitForSelector('#modal',{state:'detached'});assert.ok((await rows(table)).some(r=>r.name===name));check(table+' actual save button and required validation');
  }
  await page.evaluate(()=>go('laporan'));await page.waitForTimeout(1600);await page.locator('.report-tabs button[data-report="finance"]').click();await page.waitForTimeout(1000);
  const financePrefix=await page.locator('#finPeriod,#financePeriod').evaluate(el=>el.id.slice(0,-6));
  const today=await page.evaluate(()=>{const d=new Date(),pad=n=>String(n).padStart(2,'0');return{month:d.getFullYear()+'-'+pad(d.getMonth()+1)+'-01',quarter:(()=>{d.setDate(d.getDate()-89);return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())})()}});
  await page.selectOption('#'+financePrefix+'Period','month');await page.waitForFunction(({prefix,value})=>document.getElementById(prefix+'From').value===value,{prefix:financePrefix,value:today.month});check('active finance report uses the selected calendar month');
  await page.selectOption('#'+financePrefix+'Period','all');await page.waitForFunction(prefix=>!document.getElementById(prefix+'From').value&&!document.getElementById(prefix+'To').value,financePrefix);check('active finance report all-period reset');
  await page.evaluate(id=>openProject(id),id);await page.waitForTimeout(500);
  for(const [progress,status] of [[0.01,'AWASI'],[0,'BERISIKO']]){
   await page.evaluate(({progress})=>{state.summary.find(p=>p.project_id===state.selected).project_progress=progress;state.detail.fin=[{transaction_type:'KELUAR',category:'Material',amount:1800000}];setTab('cost')},{progress});await page.waitForSelector('#cost-control-v7');assert.ok((await page.locator('#cost-control-v7').innerText()).includes(status));check('cost V7 deployed Health threshold '+status);
  }
  await enter('konstruva');assert.equal((await rows('projects')).length,6);check('KONSTRUVA data isolated from MASTER preview');
  await enter('klien-baru');assert.equal((await rows('projects')).length,6);check('new client uses same source and isolated data');
  for(const role of ['direktur','keuangan','marketing','pelaksana']){await enter('master',role);assert.equal(await page.evaluate(async()=>(await sb.auth.getSession()).data.session.user.email),role+'@preview.invalid');if(role==='pelaksana'){const rejected=await page.evaluate(()=>sb.from('projects').insert({project_code:'DENIED',project_name:'Denied'}));assert.ok(rejected.error);check('preview adapter rejects unauthorized direct write')}check('role '+role+' dashboard');}
  await enter('master');await page.evaluate(()=>logout());await page.waitForSelector('#email');await page.waitForTimeout(400);await page.fill('#email','admin@preview.invalid');await page.fill('#password','Preview123!');await page.click('#loginBtn');await page.waitForSelector('.dashboard-head');check('logout and preview credential login');
  await page.goto(origin+'/');await page.selectOption('#tenant','master');await page.click('#reset');await page.selectOption('#role','admin');await page.click('#open');await page.waitForSelector('.dashboard-head');assert.equal((await rows('projects')).length,6);check('reset selected tenant restores seed');
  await page.goto(origin+'/');await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('#open').isVisible());await page.screenshot({path:path.join(path.dirname(output),'preview-portal.png'),fullPage:true});check('mobile preview portal');
  assert.deepEqual(external,[]);assert.deepEqual(missing,[]);assert.deepEqual(errors,[]);check('zero external requests, 404s and JavaScript errors');
  fs.writeFileSync(output,JSON.stringify({passed:true,checks,errors,external,missing,scope:'synthetic local browser simulation; no production database requests'},null,2)+'\n');
 }catch(error){console.error(JSON.stringify({errors,external,missing,page:await page.evaluate(()=>({text:document.body.innerText,project:window.state?.detail?.project,selected:window.state?.selected}))},null,2));await page.screenshot({path:path.join(path.dirname(output),'preview-failure.png'),fullPage:true});throw error}finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
