const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={window:{},Map,Set};vm.runInNewContext(fs.readFileSync('foundation/repository.js','utf8'),context);const repo=context.window.SiKoyekRepository;
function client(data,fail){let calls=0;return {get calls(){return calls},from(table){let filter=()=>true,start=0,end=Infinity,single=false,count=false;const b={select(_,opts){count=opts?.head;return b},eq(k,v){filter=x=>x[k]===v;return b},in(k,v){filter=x=>v.includes(x[k]);return b},range(s,e){start=s;end=e;return b},order(){return b},single(){single=true;return b},then(resolve){calls++;const rows=(data[table]||[]).filter(filter);return Promise.resolve({data:count?null:single?rows[0]:rows.slice(start,end+1),count:rows.length,error:fail===table?{message:'fixture error'}:null}).then(resolve)}};return b}}}
test('batch retains Closed project lock rules for every state',async()=>{const projects=[{id:'new',status:'RENCANA'},{id:'started',status:'JALAN'},{id:'progress',status:'RENCANA'},{id:'finance',status:'RENCANA'},{id:'percent',status:'RENCANA',project_progress:0.1}];const c=client({projects,progress_records:[{project_id:'progress'}],financial_transactions:[{project_id:'finance'}]});const result=await repo.lifecycleList(c,projects.map(p=>p.id));assert.equal(c.calls,3);assert.equal(result.get('new').started,false);for(const p of projects.slice(1))assert.equal(result.get(p.id).started,true);assert.equal((await repo.lifecycle(c,'new')).started,false)});
test('history beyond first API page is still considered when locking',async()=>{const records=Array.from({length:1000},()=>({project_id:'a'}));records.push({project_id:'b'});const c=client({projects:[{id:'a',status:'RENCANA'},{id:'b',status:'RENCANA'}],progress_records:records});const r=await repo.lifecycleList(c,['a','b']);assert.equal(r.get('b').started,true);assert.equal(c.calls,4)});
test('failed lifecycle read throws; UI must not treat missing data as editable',async()=>{const c=client({projects:[{id:'p',status:'RENCANA'}]},'financial_transactions');await assert.rejects(repo.lifecycleList(c,['p']));await assert.rejects(repo.lifecycle(c,'p'))});
test('project list chunks keep filters bounded above 100 projects',async()=>{const projects=Array.from({length:203},(_,i)=>({id:'p'+i,status:'RENCANA'}));const c=client({projects});const r=await repo.lifecycleList(c,projects.map(p=>p.id));assert.equal(r.size,203);assert.equal(c.calls,9)});

test('detail render uses loaded history while action checks remain separate',()=>{const project={id:'p',status:'RENCANA'};assert.equal(repo.lifecycleFromDetail({project,progress:[],fin:[]}).started,false);assert.equal(repo.lifecycleFromDetail({project,progress:[{}],fin:[]}).started,true);assert.equal(repo.lifecycleFromDetail({project,progress:[],fin:[{}]}).started,true);assert.equal(repo.lifecycleFromDetail({project,progress:[],fin:[],readError:{message:'error'}}),null);assert.equal(repo.lifecycleFromDetail({project}),null)});
