(function(){
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const db=()=>sb, q=id=>document.getElementById(id);
  const defs={
    project:{table:'project_categories',title:'Kategori Proyek',desc:'Pilihan kategori saat membuat proyek.',id:'md-project-cats'},
    finance:{table:'transaction_categories',title:'Kategori Keuangan',desc:'Kategori transaksi keuangan.',id:'md-finance-cats'},
    payment:{table:'payment_methods',title:'Metode Pembayaran',desc:'Metode pembayaran transaksi.',id:'md-payment-methods'}
  };
  async function list(table){const {data,error}=await db().from(table).select('id,name,sort_order,is_active').order('sort_order').order('name');if(error)throw error;return data||[]}
  async function managers(){const {data,error}=await db().from('project_managers').select('id,name,code,phone,email,sort_order,is_active').order('sort_order').order('name');if(error)throw error;return data||[]}
  function navButton(){const nav=document.querySelector('.sidebar .nav');if(!nav||nav.querySelector('[data-master-data-nav]'))return;const b=document.createElement('button');b.type='button';b.dataset.masterDataNav='1';b.textContent='Master Data';b.onclick=openMasterData;nav.appendChild(b)}
  function cleanProjectCategoryControl(){document.querySelectorAll('.category-tools,.step1-category-tools,[data-p6-cat-master]').forEach(x=>(x.closest?.('.category-tools,.step1-category-tools')||x).remove())}
  const mdCard=(cls,title,desc,fn)=>`<section class="card md-card"><div class="md-card-head"><div><h2>${title}</h2><p>${desc}</p></div><button class="btn primary" type="button" onclick="${fn}">+ Tambah</button></div><div id="${cls}" class="md-table-wrap"><div class="empty">Memuat...</div></div></section>`;
  function masterHTML(){return `<div class="md-page"><div class="md-top"><div><h1>Master Data</h1><p>Kelola data referensi untuk Project dan Keuangan.</p></div><button class="btn ghost" type="button" onclick="go('projects')">← Kembali ke Project</button></div><div class="md-grid">${mdCard('md-project-cats',defs.project.title,defs.project.desc,'mdAddProjectCategory()')}${mdCard('md-managers','Project Manager','Daftar Project Manager aktif.','mdAddManager()')}${mdCard('md-finance-cats',defs.finance.title,defs.finance.desc,'mdAddFinanceCategory()')}${mdCard('md-payment-methods',defs.payment.title,defs.payment.desc,'mdAddPaymentMethod()')}</div></div>`}
  function renderList(elId,rows,editFn,deleteFn){const w=q(elId);if(!w)return;w.innerHTML=rows.map(x=>`<div class="md-row"><div><strong>${esc(x.name)}</strong><small>Urutan ${Number(x.sort_order||0)}</small></div><span class="md-status ${x.is_active?'on':'off'}">${x.is_active?'AKTIF':'NONAKTIF'}</span><div class="md-actions"><button type="button" class="btn ghost" style="font-size:13px;padding:8px 12px" onclick="${editFn}('${x.id}')">Edit</button><button type="button" class="btn danger" style="font-size:13px;padding:8px 12px" onclick="${deleteFn}('${x.id}','${esc(x.name)}')">Hapus</button></div></div>`).join('')||'<div class="empty">Belum ada data.</div>'}
  function renderManagerList(rows,editFn,deleteFn){const w=q('md-managers');if(!w)return;w.innerHTML=rows.map(x=>`<div class="md-row md-manager-row"><div class="md-manager-order">Urutan ${Number(x.sort_order||0)}</div><div class="md-manager-code">${esc(x.code||'-')}</div><div class="md-manager-name"><strong>${esc(x.name)}</strong></div><span class="md-status ${x.is_active?'on':'off'}">${x.is_active?'AKTIF':'NONAKTIF'}</span><div class="md-actions"><button type="button" class="btn ghost" style="font-size:13px;padding:8px 12px" onclick="${editFn}('${x.id}')">Edit</button><button type="button" class="btn danger" style="font-size:13px;padding:8px 12px" onclick="${deleteFn}('${x.id}','${esc(x.name)}')">Hapus</button></div></div>`).join('')||'<div class="empty">Belum ada data.</div>'}
  async function refresh(){try{const [pc,pm,fc,pay]=await Promise.all([list('project_categories'),managers(),list('transaction_categories'),list('payment_methods')]);renderList('md-project-cats',pc,'mdEditProjectCategory','mdDeleteProjectCategory');renderManagerList(pm,'mdEditManager','mdDeleteManager');renderList('md-finance-cats',fc,'mdEditFinanceCategory','mdDeleteFinanceCategory');renderList('md-payment-methods',pay,'mdEditPaymentMethod','mdDeletePaymentMethod')}catch(e){toast(e?.message||'Gagal memuat Master Data')}}
  function openMasterData(){state.page='master-data';state.selected=null;state.detail=null;const page=q('page');if(page){page.innerHTML=masterHTML();refresh()}document.querySelectorAll('.sidebar .nav button').forEach(b=>b.classList.remove('active'));document.querySelector('[data-master-data-nav]')?.classList.add('active');cleanProjectCategoryControl()}
  window.openMasterData=openMasterData;
  window.mdAddProjectCategory=function(){modal('Tambah Kategori Proyek',`<div class="field"><label>Nama Kategori *</label><input id="md_name"></div><div class="field"><label>Urutan</label><input id="md_sort" type="number" value="1"></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveProjectCategory()">Simpan</button></div>`)};
  window.mdSaveProjectCategory=async function(){const name=q('md_name')?.value.trim(),sort=Number(q('md_sort')?.value||0);if(!name){toast('Nama kategori wajib diisi');return}const {error}=await db().from('project_categories').insert({name,sort_order:sort,is_active:true});if(error){toast(error.message);return}closeModal();toast('Kategori proyek ditambahkan');refresh()};
  window.mdEditProjectCategory=async function(id){const {data,error}=await db().from('project_categories').select('*').eq('id',id).single();if(error){toast(error.message);return}modal('Edit Kategori Proyek',`<div class="field"><label>Nama Kategori *</label><input id="md_name" value="${esc(data.name)}"></div><div class="field"><label>Urutan</label><input id="md_sort" type="number" value="${Number(data.sort_order||0)}"></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveProjectCategoryEdit('${id}')">Simpan</button></div>`)};
  window.mdSaveProjectCategoryEdit=async function(id){const name=q('md_name')?.value.trim(),sort=Number(q('md_sort')?.value||0);if(!name){toast('Nama kategori wajib diisi');return}const {error}=await db().from('project_categories').update({name,sort_order:sort,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}closeModal();refresh()};
  window.mdDeleteProjectCategory=function(id,name){modal('Hapus Kategori Proyek',`<p>Yakin menghapus <strong>${esc(name)}</strong>?</p><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn danger" onclick="mdConfirmDeleteProjectCategory('${id}')">Hapus Data</button></div>`)};
  window.mdConfirmDeleteProjectCategory=async function(id){const {error}=await db().from('project_categories').delete().eq('id',id);if(error){toast(error.message);return}closeModal();refresh()};
  window.mdAddManager=function(){modal('Tambah Project Manager',`<div class="formgrid"><div class="field"><label>Nama *</label><input id="md_pm_name"></div><div class="field"><label>Kode *</label><input id="md_pm_code" placeholder="PM-001"></div><div class="field"><label>No. Telepon</label><input id="md_pm_phone"></div><div class="field"><label>Email</label><input id="md_pm_email" type="email"></div><div class="field"><label>Urutan</label><input id="md_pm_sort" type="number" value="1"></div></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveManager()">Simpan</button></div>`)};
  window.mdSaveManager=async function(){const row={name:q('md_pm_name')?.value.trim(),code:q('md_pm_code')?.value.trim(),phone:q('md_pm_phone')?.value.trim()||null,email:q('md_pm_email')?.value.trim()||null,sort_order:Number(q('md_pm_sort')?.value||0),is_active:true};if(!row.name||!row.code){toast('Nama dan kode wajib diisi');return}const {error}=await db().from('project_managers').insert(row);if(error){toast(error.message);return}closeModal();refresh()};
  window.mdEditManager=async function(id){const {data,error}=await db().from('project_managers').select('*').eq('id',id).single();if(error){toast(error.message);return}modal('Edit Project Manager',`<div class="formgrid"><div class="field"><label>Nama *</label><input id="md_pm_name" value="${esc(data.name)}"></div><div class="field"><label>Kode *</label><input id="md_pm_code" value="${esc(data.code)}"></div><div class="field"><label>No. Telepon</label><input id="md_pm_phone" value="${esc(data.phone||'')}"></div><div class="field"><label>Email</label><input id="md_pm_email" value="${esc(data.email||'')}"></div><div class="field"><label>Urutan</label><input id="md_pm_sort" type="number" value="${Number(data.sort_order||0)}"></div></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveManagerEdit('${id}')">Simpan</button></div>`)};
  window.mdSaveManagerEdit=async function(id){const row={name:q('md_pm_name')?.value.trim(),code:q('md_pm_code')?.value.trim(),phone:q('md_pm_phone')?.value.trim()||null,email:q('md_pm_email')?.value.trim()||null,sort_order:Number(q('md_pm_sort')?.value||0),updated_at:new Date().toISOString()};if(!row.name||!row.code){toast('Nama dan kode wajib diisi');return}const {error}=await db().from('project_managers').update(row).eq('id',id);if(error){toast(error.message);return}closeModal();refresh()};
  window.mdDeleteManager=function(id,name){modal('Hapus Project Manager',`<p>Yakin menghapus <strong>${esc(name)}</strong>?</p><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn danger" onclick="mdConfirmDeleteManager('${id}')">Hapus Data</button></div>`)};
  window.mdConfirmDeleteManager=async function(id){const {error}=await db().from('project_managers').delete().eq('id',id);if(error){toast(error.message);return}closeModal();refresh()};
  async function add(table,title){const name=q('md_name')?.value.trim(),sort=Number(q('md_sort')?.value||0);if(!name){toast('Nama wajib diisi');return}const {error}=await db().from(table).insert({name,sort_order:sort,is_active:true});if(error){toast(error.message);return}closeModal();toast(title+' ditambahkan');refresh()}
  window.mdAddFinanceCategory=function(){modal('Tambah Kategori Keuangan',`<div class="field"><label>Nama Kategori *</label><input id="md_name" placeholder="Contoh: Material"></div><div class="field"><label>Urutan</label><input id="md_sort" type="number" value="1"></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="add('transaction_categories','Kategori Keuangan')">Simpan</button></div>`)};
  window.mdAddPaymentMethod=function(){modal('Tambah Metode Pembayaran',`<div class="field"><label>Nama Metode *</label><input id="md_name" placeholder="Contoh: Transfer"></div><div class="field"><label>Urutan</label><input id="md_sort" type="number" value="1"></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="add('payment_methods','Metode Pembayaran')">Simpan</button></div>`)};
  async function edit(table,title,id){const {data,error}=await db().from(table).select('*').eq('id',id).single();if(error){toast(error.message);return}modal('Edit '+title,`<div class="field"><label>Nama *</label><input id="md_name" value="${esc(data.name)}"></div><div class="field"><label>Urutan</label><input id="md_sort" type="number" value="${Number(data.sort_order||0)}"></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="saveEdit('${table}','${title}','${id}')">Simpan</button></div>`)}
  window.mdEditFinanceCategory=id=>edit('transaction_categories','Kategori Keuangan',id);
  window.mdEditPaymentMethod=id=>edit('payment_methods','Metode Pembayaran',id);
  window.saveEdit=async function(table,title,id){const name=q('md_name')?.value.trim(),sort=Number(q('md_sort')?.value||0);if(!name){toast('Nama wajib diisi');return}const {error}=await db().from(table).update({name,sort_order:sort,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}closeModal();toast(title+' diperbarui');refresh()};
  window.mdDeleteFinanceCategory=(id,name)=>del('transaction_categories','Kategori Keuangan',id,name);
  window.mdDeletePaymentMethod=(id,name)=>del('payment_methods','Metode Pembayaran',id,name);
  function del(table,title,id,name){modal('Hapus '+title,`<p>Yakin menghapus <strong>${esc(name)}</strong>?</p><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn danger" onclick="confirmDel('${table}','${id}')">Hapus Data</button></div>`)}
  window.confirmDel=async function(table,id){const {error}=await db().from(table).delete().eq('id',id);if(error){toast(error.message);return}closeModal();refresh()};
  async function syncSelect(id,table,placeholder){const el=q(id);if(!el||el.dataset.mdSync==='1')return;el.dataset.mdSync='1';try{const current=el.value||'';const listRows=(await list(table)).filter(x=>x.is_active);let sel=el;if(el.tagName!=='SELECT'){sel=document.createElement('select');sel.id=id;sel.name=id;sel.className=el.className;el.replaceWith(sel)}sel.innerHTML=`<option value="">${placeholder}</option>`+listRows.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');if(current)sel.value=current}catch(e){toast(e?.message||'Gagal memuat master')}}
  function observe(){navButton();cleanProjectCategoryControl();if(document.querySelector('#page .md-page')&&!q('md-master-ready')){const marker=document.createElement('span');marker.id='md-master-ready';marker.hidden=true;document.querySelector('#page .md-page').appendChild(marker);refresh()}syncSelect('f_mgr','project_managers','Pilih Project Manager...').catch(()=>{});syncSelect('tx_cat','transaction_categories','Pilih kategori...').catch(()=>{});syncSelect('tx_method','payment_methods','Pilih metode...').catch(()=>{})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
  new MutationObserver(()=>{clearTimeout(window.__mdTimer);window.__mdTimer=setTimeout(observe,120)}).observe(document.body,{childList:true,subtree:true});
})();
