(function(){
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const db=()=>{if(typeof sb!=='undefined'&&sb)return sb;throw new Error('Koneksi database belum siap.')};
  function navButton(){const nav=document.querySelector('.sidebar .nav');if(!nav||nav.querySelector('[data-master-data-nav]'))return;const b=document.createElement('button');b.type='button';b.dataset.masterDataNav='1';b.textContent='Master Data';b.onclick=()=>openMasterData();nav.appendChild(b)}
  function cleanProjectCategoryControl(){document.querySelectorAll('.category-tools,.step1-category-tools,[data-p6-cat-master]').forEach(x=>{const row=x.closest?.('.category-tools,.step1-category-tools');(row||x).remove()})}
  function cleanDashboardExtras(){['decision-engine-v1-card','health-engine-v1-card'].forEach(id=>document.getElementById(id)?.remove());document.querySelectorAll('[data-dashboard-graph-card]').forEach(x=>x.remove())}
  async function getCategories(){const {data,error}=await db().from('project_categories').select('id,name,sort_order,is_active').order('sort_order').order('name');if(error)throw error;return data||[]}
  async function getManagers(){const {data,error}=await db().from('project_managers').select('id,name,code,phone,email,sort_order,is_active').order('sort_order').order('name');if(error)throw error;return data||[]}
  function masterHTML(){return `<div class="md-page"><div class="md-top"><div><div class="md-kicker">MASTER DATA</div><h1>Master Data</h1><p>Kelola data referensi yang digunakan oleh modul Project.</p></div><button class="btn ghost" type="button" onclick="go('projects')">← Kembali ke Project</button></div><div class="md-grid"><section class="card md-card"><div class="md-card-head"><div><h2>Kategori Proyek</h2><p>Dipakai sebagai pilihan kategori saat membuat proyek.</p></div><button class="btn primary" type="button" onclick="mdAddCategory()">+ Tambah</button></div><div id="mdCategories" class="md-table-wrap"><div class="empty">Memuat...</div></div></section><section class="card md-card"><div class="md-card-head"><div><h2>Project Manager</h2><p>Daftar Project Manager aktif untuk dipilih pada data proyek.</p></div><button class="btn primary" type="button" onclick="mdAddManager()">+ Tambah</button></div><div id="mdManagers" class="md-table-wrap"><div class="empty">Memuat...</div></div></section></div><div class="md-note">Material dan Supplier akan ditambahkan sebagai master berikutnya setelah struktur Costing kita finalkan.</div></div>`}
  function bindDeleteButtons(){document.querySelectorAll('[data-md-delete-cat]').forEach(b=>b.onclick=()=>mdDeleteCategory(b.dataset.id,b.dataset.name));document.querySelectorAll('[data-md-delete-pm]').forEach(b=>b.onclick=()=>mdDeleteManager(b.dataset.id,b.dataset.name))}
  function renderCategories(rows){const w=document.getElementById('mdCategories');if(!w)return;w.innerHTML=rows.map(x=>`<div class="md-row"><div><strong>${esc(x.name)}</strong><small>Urutan ${Number(x.sort_order||0)}</small></div><span class="md-status ${x.is_active?'on':'off'}">${x.is_active?'AKTIF':'NONAKTIF'}</span><div class="md-actions"><button type="button" class="btn ghost" style="font-size:13px;padding:8px 12px" onclick="mdEditCategory('${x.id}')">Edit</button><button type="button" class="btn danger" data-md-delete-cat data-id="${esc(x.id)}" data-name="${esc(x.name)}" style="font-size:13px;padding:8px 12px">Hapus</button></div></div>`).join('')||'<div class="empty">Belum ada kategori.</div>';bindDeleteButtons()}
  function renderManagers(rows){const w=document.getElementById('mdManagers');if(!w)return;w.innerHTML=rows.map(x=>`<div class="md-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.code)}</small></div><span class="md-status ${x.is_active?'on':'off'}">${x.is_active?'AKTIF':'NONAKTIF'}</span><div class="md-actions"><button type="button" class="btn ghost" style="font-size:13px;padding:8px 12px" onclick="mdEditManager('${x.id}')">Edit</button><button type="button" class="btn danger" data-md-delete-pm data-id="${esc(x.id)}" data-name="${esc(x.name)}" style="font-size:13px;padding:8px 12px">Hapus</button></div></div>`).join('')||'<div class="empty">Belum ada Project Manager.</div>';bindDeleteButtons()}
  async function refreshMasterData(){try{const [c,m]=await Promise.all([getCategories(),getManagers()]);renderCategories(c);renderManagers(m)}catch(e){const msg=e?.message||'Gagal memuat Master Data';toast(msg);const a=document.getElementById('mdCategories'),b=document.getElementById('mdManagers');if(a)a.innerHTML='<div class="empty">Gagal memuat data.</div>';if(b)b.innerHTML='<div class="empty">Gagal memuat data.</div>'}}
  function openMasterData(){state.page='master-data';state.selected=null;state.detail=null;cleanDashboardExtras();const page=document.getElementById('page');if(page){page.innerHTML=masterHTML();refreshMasterData()}document.querySelectorAll('.sidebar .nav button').forEach(b=>b.classList.remove('active'));document.querySelector('[data-master-data-nav]')?.classList.add('active');cleanProjectCategoryControl()}
  window.openMasterData=openMasterData;
  window.mdAddCategory=function(){modal('Tambah Kategori Proyek',`<div class="field"><label>Nama Kategori *</label><input id="md_cat_name" placeholder="Contoh: Pembangunan Gedung"></div><div class="field"><label>Urutan</label><input id="md_cat_sort" type="number" min="0" value="1"></div><div class="formactions"><button type="button" class="btn ghost" onclick="closeModal()">Batal</button><button type="button" class="btn primary" onclick="mdSaveCategory()">Simpan</button></div>`) }; 
  window.mdSaveCategory=async function(){const name=document.getElementById('md_cat_name')?.value.trim(),sort=Number(document.getElementById('md_cat_sort')?.value||0);if(!name){toast('Nama kategori wajib diisi');return}const {error}=await db().from('project_categories').insert({name,sort_order:sort,is_active:true});if(error){toast(error.message);return}closeModal();toast('Kategori berhasil ditambahkan');await refreshMasterData()};
  window.mdEditCategory=async function(id){const {data,error}=await db().from('project_categories').select('id,name,sort_order,is_active').eq('id',id).single();if(error){toast(error.message);return}modal('Edit Kategori Proyek',`<div class="field"><label>Nama Kategori *</label><input id="md_cat_name" value="${esc(data.name)}"></div><div class="field"><label>Urutan</label><input id="md_cat_sort" type="number" min="0" value="${Number(data.sort_order||0)}"></div><div class="field"><label>Status</label><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;border:1px solid #e5eaf1;border-radius:10px"><span class="md-status ${data.is_active?'on':'off'}">${data.is_active?'AKTIF':'NONAKTIF'}</span><button type="button" class="btn ${data.is_active?'danger':'ghost'}" style="font-size:13px;padding:8px 12px" onclick="mdToggleCategory('${id}',${!data.is_active})">${data.is_active?'Nonaktifkan':'Aktifkan'}</button></div></div><div class="formactions"><span style="flex:1"></span><button type="button" class="btn ghost" onclick="closeModal()">Batal</button><button type="button" class="btn primary" onclick="mdSaveCategoryEdit('${id}')">Simpan</button></div>`) };
  window.mdSaveCategoryEdit=async function(id){const name=document.getElementById('md_cat_name')?.value.trim(),sort=Number(document.getElementById('md_cat_sort')?.value||0);if(!name){toast('Nama kategori wajib diisi');return}const {error}=await db().from('project_categories').update({name,sort_order:sort,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}closeModal();toast('Kategori diperbarui');await refreshMasterData()};
  window.mdToggleCategory=async function(id,active){const {error}=await db().from('project_categories').update({is_active:active,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}closeModal();toast(active?'Kategori diaktifkan':'Kategori dinonaktifkan');await refreshMasterData()};
  window.mdDeleteCategory=function(id,name){if(!id){toast('ID kategori tidak ditemukan');return}modal('Hapus Kategori Proyek',`<p style="margin:0 0 14px;color:var(--muted)">Yakin ingin menghapus kategori <strong>${esc(name)}</strong>?</p><p class="note">Data proyek yang sudah memakai kategori ini tidak ikut dihapus.</p><div class="formactions"><button type="button" class="btn ghost" onclick="closeModal()">Batal</button><button type="button" class="btn danger" onclick="mdConfirmDeleteCategory('${id}')">Hapus Data</button></div>`) };
  window.mdConfirmDeleteCategory=async function(id){const {error}=await db().from('project_categories').delete().eq('id',id);if(error){toast('Kategori tidak dapat dihapus: '+error.message);return}const {data:still,error:verify}=await db().from('project_categories').select('id').eq('id',id).maybeSingle();if(verify){toast('Verifikasi penghapusan gagal: '+verify.message);return}if(still){toast('Data masih ada di database.');return}closeModal();toast('Kategori berhasil dihapus');await refreshMasterData()};
  window.mdAddManager=function(){modal('Tambah Project Manager',`<div class="formgrid"><div class="field"><label>Nama *</label><input id="md_pm_name"></div><div class="field"><label>Kode *</label><input id="md_pm_code" placeholder="PM-001"></div><div class="field"><label>No. Telepon</label><input id="md_pm_phone"></div><div class="field"><label>Email</label><input id="md_pm_email" type="email"></div><div class="field"><label>Urutan</label><input id="md_pm_sort" type="number" min="0" value="1"></div></div><div class="formactions"><button type="button" class="btn ghost" onclick="closeModal()">Batal</button><button type="button" class="btn primary" onclick="mdSaveManager()">Simpan</button></div>`) };
  window.mdSaveManager=async function(){const row={name:document.getElementById('md_pm_name')?.value.trim(),code:document.getElementById('md_pm_code')?.value.trim(),phone:document.getElementById('md_pm_phone')?.value.trim()||null,email:document.getElementById('md_pm_email')?.value.trim()||null,sort_order:Number(document.getElementById('md_pm_sort')?.value||0),is_active:true};if(!row.name||!row.code){toast('Nama dan kode wajib diisi');return}const {error}=await db().from('project_managers').insert(row);if(error){toast(error.message);return}closeModal();toast('Project Manager ditambahkan');await refreshMasterData()};
  window.mdEditManager=async function(id){const {data,error}=await db().from('project_managers').select('id,name,code,phone,email,sort_order,is_active').eq('id',id).single();if(error){toast(error.message);return}modal('Edit Project Manager',`<div class="formgrid"><div class="field"><label>Nama *</label><input id="md_pm_name" value="${esc(data.name)}"></div><div class="field"><label>Kode *</label><input id="md_pm_code" value="${esc(data.code)}"></div><div class="field"><label>No. Telepon</label><input id="md_pm_phone" value="${esc(data.phone||'')}"></div><div class="field"><label>Email</label><input id="md_pm_email" type="email" value="${esc(data.email||'')}"></div><div class="field"><label>Urutan</label><input id="md_pm_sort" type="number" value="${Number(data.sort_order||0)}"></div></div><div class="field"><label>Status</label><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;border:1px solid #e5eaf1;border-radius:10px"><span class="md-status ${data.is_active?'on':'off'}">${data.is_active?'AKTIF':'NONAKTIF'}</span><button type="button" class="btn ${data.is_active?'danger':'ghost'}" style="font-size:13px;padding:8px 12px" onclick="mdToggleManager('${id}',${!data.is_active})">${data.is_active?'Nonaktifkan':'Aktifkan'}</button></div></div><div class="formactions"><span style="flex:1"></span><button type="button" class="btn ghost" onclick="closeModal()">Batal</button><button type="button" class="btn primary" onclick="mdSaveManagerEdit('${id}')">Simpan</button></div>`) };
  window.mdSaveManagerEdit=async function(id){const row={name:document.getElementById('md_pm_name')?.value.trim(),code:document.getElementById('md_pm_code')?.value.trim(),phone:document.getElementById('md_pm_phone')?.value.trim()||null,email:document.getElementById('md_pm_email')?.value.trim()||null,sort_order:Number(document.getElementById('md_pm_sort')?.value||0),updated_at:new Date().toISOString()};if(!row.name||!row.code){toast('Nama dan kode wajib diisi');return}const {error}=await db().from('project_managers').update(row).eq('id',id);if(error){toast(error.message);return}closeModal();toast('Project Manager diperbarui');await refreshMasterData()};
  window.mdToggleManager=async function(id,active){const {error}=await db().from('project_managers').update({is_active:active,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}closeModal();toast(active?'Project Manager diaktifkan':'Project Manager dinonaktifkan');await refreshMasterData()};
  window.mdDeleteManager=function(id,name){if(!id){toast('ID Project Manager tidak ditemukan');return}modal('Hapus Project Manager',`<p style="margin:0 0 14px;color:var(--muted)">Yakin ingin menghapus <strong>${esc(name)}</strong>?</p><p class="note">Data proyek yang sudah memakai nama ini tidak ikut dihapus.</p><div class="formactions"><button type="button" class="btn ghost" onclick="closeModal()">Batal</button><button type="button" class="btn danger" onclick="mdConfirmDeleteManager('${id}')">Hapus Data</button></div>`) };
  window.mdConfirmDeleteManager=async function(id){const {error}=await db().from('project_managers').delete().eq('id',id);if(error){toast('Project Manager tidak dapat dihapus: '+error.message);return}const {data:still,error:verify}=await db().from('project_managers').select('id').eq('id',id).maybeSingle();if(verify){toast('Verifikasi penghapusan gagal: '+verify.message);return}if(still){toast('Data masih ada di database.');return}closeModal();toast('Project Manager berhasil dihapus');await refreshMasterData()};
  async function populateProjectManagerSelect(el){if(!el)return;const current=el.value||'';el.dataset.mdSynced='1';try{const rows=(await getManagers()).filter(x=>x.is_active);el.innerHTML='<option value="">Pilih Project Manager...</option>'+rows.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} (${esc(x.code)})</option>`).join('');if(rows.some(x=>x.name===current))el.value=current}catch(e){el.innerHTML='<option value="">Pilih Project Manager...</option>';toast(e?.message||'Gagal memuat Project Manager')}}
  function syncProjectManagerField(){let el=document.getElementById('f_mgr');if(!el||el.dataset.mdSynced==='1')return;if(el.tagName==='SELECT'){populateProjectManagerSelect(el);return}const current=el.value||'';const select=document.createElement('select');select.id='f_mgr';select.name='f_mgr';select.className=el.className;select.dataset.mdSynced='1';el.replaceWith(select);populateProjectManagerSelect(select)}
  function observe(){navButton();cleanProjectCategoryControl();syncProjectManagerField();if(document.querySelector('#page .md-page'))cleanDashboardExtras()}
  const obs=new MutationObserver(()=>{clearTimeout(window.__mdTimer);window.__mdTimer=setTimeout(observe,120)});
  function boot(){observe();obs.observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
