(function(){
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const sbx=()=>window.sb;
  function navButton(){const nav=document.querySelector('.sidebar .nav');if(!nav||nav.querySelector('[data-master-data-nav]'))return;const b=document.createElement('button');b.type='button';b.dataset.masterDataNav='1';b.textContent='Master Data';b.onclick=()=>openMasterData();nav.appendChild(b)}
  function cleanProjectCategoryControl(){document.querySelectorAll('.category-tools,.step1-category-tools,[data-p6-cat-master]').forEach(x=>{const row=x.classList?.contains('category-tools')||x.classList?.contains('step1-category-tools')?x:x.closest('.category-tools,.step1-category-tools');if(row)row.remove();else x.remove()})}
  async function getCategories(){const {data,error}=await sbx().from('project_categories').select('id,name,sort_order,is_active').order('sort_order').order('name');if(error)throw error;return data||[]}
  async function getManagers(){const {data,error}=await sbx().from('project_managers').select('id,name,code,phone,email,sort_order,is_active').order('sort_order').order('name');if(error)throw error;return data||[]}
  function masterHTML(){return `<div class="md-page"><div class="md-top"><div><div class="md-kicker">MASTER DATA</div><h1>Master Data</h1><p>Kelola data referensi yang digunakan oleh modul Project.</p></div><button class="btn ghost" onclick="go('projects')">← Kembali ke Project</button></div><div class="md-grid"><section class="card md-card"><div class="md-card-head"><div><h2>Kategori Proyek</h2><p>Dipakai sebagai pilihan kategori saat membuat proyek.</p></div><button class="btn primary" onclick="mdAddCategory()">+ Tambah</button></div><div id="mdCategories" class="md-table-wrap"><div class="empty">Memuat...</div></div></section><section class="card md-card"><div class="md-card-head"><div><h2>Project Manager</h2><p>Daftar Project Manager aktif untuk dipilih pada data proyek.</p></div><button class="btn primary" onclick="mdAddManager()">+ Tambah</button></div><div id="mdManagers" class="md-table-wrap"><div class="empty">Memuat...</div></div></section></div><div class="md-note">Material dan Supplier akan ditambahkan sebagai master berikutnya setelah struktur Costing kita finalkan.</div></div>`}
  function renderCategories(rows){const w=document.getElementById('mdCategories');if(!w)return;w.innerHTML=rows.map(x=>`<div class="md-row"><div><strong>${esc(x.name)}</strong><small>Urutan ${Number(x.sort_order||0)}</small></div><span class="md-status ${x.is_active?'on':'off'}">${x.is_active?'AKTIF':'NONAKTIF'}</span><div class="md-actions"><button class="btn ghost" onclick="mdEditCategory('${x.id}',${JSON.stringify(x.name)})">Edit</button>${x.is_active?`<button class="btn danger" onclick="mdToggleCategory('${x.id}',false)">Nonaktifkan</button>`:`<button class="btn ghost" onclick="mdToggleCategory('${x.id}',true)">Aktifkan</button>`}</div></div>`).join('')||'<div class="empty">Belum ada kategori.</div>'}
  function renderManagers(rows){const w=document.getElementById('mdManagers');if(!w)return;w.innerHTML=rows.map(x=>`<div class="md-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.code)}</small></div><span class="md-status ${x.is_active?'on':'off'}">${x.is_active?'AKTIF':'NONAKTIF'}</span><div class="md-actions"><button class="btn ghost" onclick="mdEditManager('${x.id}',${JSON.stringify(x)})">Edit</button>${x.is_active?`<button class="btn danger" onclick="mdToggleManager('${x.id}',false)">Nonaktifkan</button>`:`<button class="btn ghost" onclick="mdToggleManager('${x.id}',true)">Aktifkan</button>`}</div></div>`).join('')||'<div class="empty">Belum ada Project Manager.</div>'}
  async function refreshMasterData(){try{const [c,m]=await Promise.all([getCategories(),getManagers()]);renderCategories(c);renderManagers(m)}catch(e){toast(e?.message||'Gagal memuat Master Data')}}
  function openMasterData(){state.page='master-data';state.selected=null;state.detail=null;const page=document.getElementById('page');if(page){page.innerHTML=masterHTML();refreshMasterData()}document.querySelectorAll('.sidebar .nav button').forEach(b=>b.classList.remove('active'));document.querySelector('[data-master-data-nav]')?.classList.add('active');cleanProjectCategoryControl()}
  window.openMasterData=openMasterData;
  window.mdAddCategory=function(){modal('Tambah Kategori Proyek',`<div class="field"><label>Nama Kategori *</label><input id="md_cat_name" placeholder="Contoh: Pembangunan Gedung"></div><div class="field"><label>Urutan</label><input id="md_cat_sort" type="number" min="0" value="1"></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveCategory()">Simpan</button></div>`)}
  window.mdSaveCategory=async function(){const name=document.getElementById('md_cat_name')?.value.trim();const sort=Number(document.getElementById('md_cat_sort')?.value||0);if(!name){toast('Nama kategori wajib diisi');return}const {error}=await sbx().from('project_categories').insert({name,sort_order:sort,is_active:true});if(error){toast(error.message);return}closeModal();toast('Kategori berhasil ditambahkan');refreshMasterData()}
  window.mdEditCategory=function(id,current){modal('Edit Kategori Proyek',`<div class="field"><label>Nama Kategori *</label><input id="md_cat_name" value="${esc(current)}"></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveCategoryEdit('${id}')">Simpan</button></div>`)}
  window.mdSaveCategoryEdit=async function(id){const name=document.getElementById('md_cat_name')?.value.trim();if(!name){toast('Nama kategori wajib diisi');return}const {error}=await sbx().from('project_categories').update({name,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}closeModal();toast('Kategori diperbarui');refreshMasterData()}
  window.mdToggleCategory=async function(id,active){const {error}=await sbx().from('project_categories').update({is_active:active,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}refreshMasterData()}
  window.mdAddManager=function(){modal('Tambah Project Manager',`<div class="formgrid"><div class="field"><label>Nama *</label><input id="md_pm_name"></div><div class="field"><label>Kode *</label><input id="md_pm_code" placeholder="PM-001"></div><div class="field"><label>No. Telepon</label><input id="md_pm_phone"></div><div class="field"><label>Email</label><input id="md_pm_email" type="email"></div><div class="field"><label>Urutan</label><input id="md_pm_sort" type="number" min="0" value="1"></div></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveManager()">Simpan</button></div>`)}
  window.mdSaveManager=async function(){const row={name:document.getElementById('md_pm_name')?.value.trim(),code:document.getElementById('md_pm_code')?.value.trim(),phone:document.getElementById('md_pm_phone')?.value.trim()||null,email:document.getElementById('md_pm_email')?.value.trim()||null,sort_order:Number(document.getElementById('md_pm_sort')?.value||0),is_active:true};if(!row.name||!row.code){toast('Nama dan kode wajib diisi');return}const {error}=await sbx().from('project_managers').insert(row);if(error){toast(error.message);return}closeModal();toast('Project Manager ditambahkan');refreshMasterData()}
  window.mdEditManager=function(id,row){modal('Edit Project Manager',`<div class="formgrid"><div class="field"><label>Nama *</label><input id="md_pm_name" value="${esc(row.name)}"></div><div class="field"><label>Kode *</label><input id="md_pm_code" value="${esc(row.code)}"></div><div class="field"><label>No. Telepon</label><input id="md_pm_phone" value="${esc(row.phone||'')}"></div><div class="field"><label>Email</label><input id="md_pm_email" type="email" value="${esc(row.email||'')}"></div><div class="field"><label>Urutan</label><input id="md_pm_sort" type="number" value="${Number(row.sort_order||0)}"></div></div><div class="formactions"><button class="btn ghost" onclick="closeModal()">Batal</button><button class="btn primary" onclick="mdSaveManagerEdit('${id}')">Simpan</button></div>`)}
  window.mdSaveManagerEdit=async function(id){const row={name:document.getElementById('md_pm_name')?.value.trim(),code:document.getElementById('md_pm_code')?.value.trim(),phone:document.getElementById('md_pm_phone')?.value.trim()||null,email:document.getElementById('md_pm_email')?.value.trim()||null,sort_order:Number(document.getElementById('md_pm_sort')?.value||0),updated_at:new Date().toISOString()};if(!row.name||!row.code){toast('Nama dan kode wajib diisi');return}const {error}=await sbx().from('project_managers').update(row).eq('id',id);if(error){toast(error.message);return}closeModal();toast('Project Manager diperbarui');refreshMasterData()}
  window.mdToggleManager=async function(id,active){const {error}=await sbx().from('project_managers').update({is_active:active,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}refreshMasterData()}
  function syncProjectManagerField(){const input=document.getElementById('f_mgr');if(!input||input.dataset.mdSynced==='1')return;const current=input.value;const select=document.createElement('select');select.id='f_mgr';select.name='f_mgr';select.className=input.className;input.replaceWith(select);getManagers().then(rows=>{const active=rows.filter(x=>x.is_active);select.innerHTML='<option value="">Pilih Project Manager...</option>'+active.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} (${esc(x.code)})</option>`).join('');if(active.some(x=>x.name===current))select.value=current;select.dataset.mdSynced='1'}).catch(()=>{select.innerHTML='<option value="">Pilih Project Manager...</option>';select.dataset.mdSynced='1'})}
  function observe(){navButton();cleanProjectCategoryControl();syncProjectManagerField()}
  const obs=new MutationObserver(()=>{clearTimeout(window.__mdTimer);window.__mdTimer=setTimeout(observe,120)});function boot(){observe();obs.observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
