const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('ui-form-pass7.js','utf8');
const css=fs.readFileSync('ui-form-pass7.css','utf8');
const pass6=fs.readFileSync('ui-form-pass6.js','utf8');
const pages=fs.readFileSync('.github/workflows/pages.yml','utf8');

assert.ok(js.includes('p6CloseCategoryMaster'),'Pass 7 close hook missing');
assert.ok(js.includes('window.p6CloseCategoryMaster=closeCategoryAndRestore'),'Category master close hook not replaced');
assert.ok(js.includes("find(m=>m.querySelector('#p6CatRows'))"),'Category modal targeting guard missing');
assert.ok(js.includes('categoryModal.remove()'),'Category modal must be removed directly');
assert.ok(js.includes('getProjectModal()'),'Existing project modal lookup missing');
assert.ok(js.includes('formifyCategoryMaster'),'Master category shell transformer missing');
assert.ok(js.includes('p6-category-side'),'Master category must use a real sidebar element');
assert.ok(js.includes('hideCategoryTopClose'),'Master category top close button guard missing');
assert.ok(js.includes("box.querySelector('.modalhead button')?.remove()"),'Master category top close button must be removed');
assert.ok(pass6.includes("box.dataset.p6==='1'||box.dataset.p6Master==='1'"),'Pass 6 must not re-transform Master Kategori on later MutationObserver passes');
assert.ok(pass6.includes("document.querySelector('#modal .modalbox .modalhead button')?.remove()"),'Pass 6 must remove Master Kategori header close at creation');
assert.ok(pass6.includes('Tutup & Kembali'),'Master Kategori must keep the single explicit close action');
assert.ok(css.includes('.modalbox.p6-form>.p6-side'),'Project side panel alignment missing');
assert.ok(css.includes('.p6-body>.modalhead h3'),'Project modal header selector missing');
assert.ok(css.includes('visibility:visible!important'),'Modal header title must be visible');
assert.ok(css.includes('height:76px!important'),'Compact modal header height missing');
assert.ok(css.includes('.modalbox:has(#p6CatRows)::before{display:none!important'),'Old pseudo sidebar must be disabled');
assert.ok(css.includes('.modalbox:has(#p6CatRows)>.p6-category-side'),'Master category real sidebar alignment missing');
assert.ok(css.includes('.modalbox:has(#p6CatRows)>.p6-body'),'Master category body alignment missing');
assert.ok(pages.includes('ui-form-pass7.js?v=1'),'Pass 7 JS deployment missing');
assert.ok(pages.includes('ui-form-pass7.css?v=1'),'Pass 7 CSS deployment missing');
console.log('UI Form Pass 7: PASS');