const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('ui-form-pass6.js','utf8');
const css=fs.readFileSync('ui-form-pass6.css','utf8');
assert.ok(js.includes('removeCategoryTools'),'Category tool cleanup missing');
assert.ok(js.includes('ensureCategoryDropdown'),'Category dropdown enforcement missing');
assert.ok(js.includes('data-p6CatMasterAttached'),'Category master guard missing');
assert.ok(css.includes('.p6-body>.modalhead'),'Modal header styling missing');
assert.ok(css.includes('.p6-body>.modalhead .modalclose'),'Modal close alignment styling missing');
console.log('UI Form Pass 6 Step 1: PASS');
