const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('ui-form-pass6.js','utf8');
const css=fs.readFileSync('ui-form-pass6.css','utf8');
const deploy=fs.readFileSync('.github/workflows/pages.yml','utf8');
assert.ok(js.includes('ensureCategoryDropdown'),'Category dropdown enforcement missing');
assert.ok(js.includes('p6OpenCategoryMaster'),'Category master control missing');
assert.ok(js.includes('p6EditCat'),'Category edit action missing');
assert.ok(js.includes('p6DeactivateCat'),'Category deactivate action missing');
assert.ok(js.includes('p6ActivateCat'),'Category activate action missing');
assert.ok(js.includes('decorateProjects'),'Project action decoration missing');
assert.ok(js.includes('p5EditProject'),'Project edit integration missing');
assert.ok(js.includes('p5DeleteProject'),'Project delete integration missing');
assert.ok(js.includes('obs.observe(document.body'),'Dynamic modal observer missing');
assert.ok(js.includes('categorySyncing'),'Category observer guard missing');
assert.ok(js.includes('categorySynced'),'Category observer completion guard missing');
assert.ok(css.includes('.modalbox.p6-form'),'Split-form visual system missing');
assert.ok(css.includes('.p6-side'),'Form side panel missing');
assert.ok(css.includes('.p6-project-actions'),'Project action styling missing');
assert.ok(css.includes('.p6-category-table'),'Category master table styling missing');
assert.ok(deploy.includes('ui-form-pass6.js?v=2'),'Pass 6 JS deployment missing');
assert.ok(deploy.includes('ui-form-pass6.css?v=2'),'Pass 6 CSS deployment missing');
console.log('UI Form Pass 6: PASS');
