const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('ui-form-fixes-v3.js','utf8');
const css=fs.readFileSync('ui-form-fixes-v3.css','utf8');
const page=fs.readFileSync('index.html','utf8');
const migration=fs.readFileSync('supabase/migrations/20260825045000_project_category_master.sql','utf8');
assert.ok(js.includes('window.nextProjectStep'),'Project wizard next handler must be globally reachable');
assert.ok(js.includes('window.prevProjectStep'),'Project wizard back handler must be globally reachable');
assert.ok(js.includes('project_categories'),'Project category master integration missing');
assert.ok(js.includes('openCategoryMaster'),'Category master UI missing');
assert.ok(js.includes("insert({name,sort_order"),'Category insert logic missing');
assert.ok(css.includes('--ux3-navy'),'Form-fix design token missing');
assert.ok(css.includes('.category-tools'),'Category master styling missing');
assert.ok(page.includes('ui-form-fixes-v3.js'),'Fix JS must be included in the canonical Pages source');
assert.ok(page.includes('ui-form-fixes-v3.css'),'Fix CSS must be included in the canonical Pages source');
assert.ok(migration.includes('project_categories'),'Category master migration missing');
console.log('UI Form Fixes V3: PASS');
