/* Synthetic preview seed only. No real client data or credentials. */
window.SiKoyekPreviewSeed=function(){
const role='admin',uid='00000000-0000-4000-8000-000000000001',user={email:'admin@preview.invalid'};
const summary=Array.from({length:6},(_,i)=>({project_id:'p'+i,project_code:'P26'+String(i+1).padStart(3,'0'),project_name:'Proyek Uji '+(i+1),contract_value:100000000+i*10000000,total_rap:80000000,project_progress:20+i*10,cost_ratio:10+i*12,rap_consumption:15+i*15,health_status:i<2?'SEHAT':i<4?'WASPADA':'BERISIKO',estimated_profit:20000000,cash_in:50000000,cash_out:30000000,net_cashflow:20000000,project_date:'2026-09-01',start_date:'2026-09-01',end_date:'2026-12-31',status:'JALAN'}));
const modules=['DASHBOARD','PROJECTS','MASTER_DATA','PROGRESS','RAP','KEUANGAN','USERS','LAPORAN'];
const permissions=modules.flatMap(m=>['VIEW','ADD','EDIT','DELETE'].map(a=>({id:m+'_'+a,module:m,action:a,name:m+' '+a})));
const allowed=permissions;
const tables={project_summary:summary,projects:summary.map(p=>({...p,id:p.project_id,owner_name:'Pemilik Uji',location:'Tasikmalaya',category:'Perumahan',project_manager:'Mandor Uji'})),profiles:['admin','direktur','keuangan','marketing','pelaksana'].map((role,i)=>({id:i===0?uid:'preview-user-'+role,full_name:'Pengguna Uji '+role,email:role+'@preview.invalid',is_active:true,role_id:role,roles:{name:role,description:role},created_at:'2026-01-01'})),roles:['admin','direktur','keuangan','marketing','pelaksana'].map(name=>({id:name,name,is_active:true})),permissions,role_permissions:['admin','direktur','keuangan','marketing','pelaksana'].flatMap(name=>permissions.filter(p=>name==='admin'||!['USERS','MASTER_DATA'].includes(p.module)&&(name==='direktur'||p.action==='VIEW')).map(p=>({role_id:name,permission_id:p.id}))),project_work_items:summary.flatMap(p=>[{id:p.project_id+'i1',project_id:p.project_id,work_name:'Pondasi',weight:0.4,sort_order:1},{id:p.project_id+'i2',project_id:p.project_id,work_name:'Dinding',weight:0.6,sort_order:2}]),project_rap:summary.map(p=>({project_id:p.project_id,material:30000000,labor:20000000,equipment:10000000,operational:10000000,subcontract:5000000,other:5000000})),progress_records:summary.map(p=>({id:p.project_id+'pr',project_id:p.project_id,work_item_id:p.project_id+'i1',progress_date:'2026-10-01',progress_percentage:0.5,notes:'Uji'})),financial_transactions:summary.flatMap(p=>[{id:p.project_id+'t1',project_id:p.project_id,transaction_date:'2026-10-01',transaction_type:'MASUK',category:'Uang Muka',amount:50000000,description:'Uji masuk',payment_method:'Transfer'},{id:p.project_id+'t2',project_id:p.project_id,transaction_date:'2026-10-02',transaction_type:'KELUAR',category:'Material',amount:30000000,description:'Uji keluar',payment_method:'Cash'}]),project_categories:[{id:'c1',name:'Perumahan',is_active:true,sort_order:1}],project_managers:[{id:'m1',name:'Mandor Uji',is_active:true,sort_order:1}],transaction_categories:[{id:'tc1',name:'Material',transaction_type:'KELUAR',is_active:true,sort_order:1}],payment_methods:[{id:'pm1',name:'Transfer',is_active:true,sort_order:1}]};
// Keep table rows consistent with the synthetic history and financial totals.
const projectColumns=['id','project_code','project_date','project_name','owner_name','category','location','contract_value','start_date','end_date','project_manager','status','project_progress'];
tables.projects=tables.projects.map(p=>Object.fromEntries(projectColumns.map(key=>[key,p[key]])));
tables.progress_records=summary.flatMap(p=>[{id:p.project_id+'pr1',project_id:p.project_id,work_item_id:p.project_id+'i1',progress_date:'2026-10-01',progress_percentage:Math.min(1,p.project_progress/40),notes:'Data uji awal'},{id:p.project_id+'pr2',project_id:p.project_id,work_item_id:p.project_id+'i2',progress_date:'2026-10-01',progress_percentage:Math.max(0,p.project_progress-40)/60,notes:'Data uji awal'}]);
const spending=[12000000,25000000,40000000,48000000,68000000,78000000];
tables.financial_transactions.filter(t=>t.transaction_type==='KELUAR').forEach((t,i)=>{t.amount=spending[i]});
return tables;
};
