-- SiKoyek V1.0 RBAC seed
-- UUIDs are generated by the target database; mappings join by stable names.

insert into public.roles (name,is_active)
values
 ('ADMIN',true),('DIREKTUR',true),('KEUANGAN',true),('MARKETING',true),('PELAKSANA',true)
on conflict (name) do update set is_active=excluded.is_active;

insert into public.permissions (module,action,name)
values
 ('dashboard','view','dashboard.view'),
 ('finance','add','finance.add'),('finance','delete','finance.delete'),('finance','edit','finance.edit'),('finance','view','finance.view'),
 ('laporan','view','laporan.view'),
 ('master_data','add','master_data.add'),('master_data','delete','master_data.delete'),('master_data','edit','master_data.edit'),('master_data','view','master_data.view'),
 ('progress','add','progress.add'),('progress','delete','progress.delete'),('progress','edit','progress.edit'),('progress','view','progress.view'),
 ('projects','add','projects.add'),('projects','delete','projects.delete'),('projects','edit','projects.edit'),('projects','view','projects.view'),
 ('rap','add','rap.add'),('rap','delete','rap.delete'),('rap','edit','rap.edit'),('rap','view','rap.view'),
 ('users','add','users.add'),('users','delete','users.delete'),('users','edit','users.edit'),('users','view','users.view')
on conflict (name) do update set module=excluded.module,action=excluded.action;

with mapping(role_name,permission_name) as (
  values
  ('ADMIN','dashboard.view'),('ADMIN','finance.add'),('ADMIN','finance.delete'),('ADMIN','finance.edit'),('ADMIN','finance.view'),('ADMIN','laporan.view'),
  ('ADMIN','master_data.add'),('ADMIN','master_data.delete'),('ADMIN','master_data.edit'),('ADMIN','master_data.view'),('ADMIN','progress.add'),('ADMIN','progress.delete'),('ADMIN','progress.edit'),('ADMIN','progress.view'),
  ('ADMIN','projects.add'),('ADMIN','projects.delete'),('ADMIN','projects.edit'),('ADMIN','projects.view'),('ADMIN','rap.add'),('ADMIN','rap.delete'),('ADMIN','rap.edit'),('ADMIN','rap.view'),('ADMIN','users.add'),('ADMIN','users.delete'),('ADMIN','users.edit'),('ADMIN','users.view'),
  ('DIREKTUR','dashboard.view'),('DIREKTUR','finance.view'),('DIREKTUR','laporan.view'),('DIREKTUR','master_data.add'),('DIREKTUR','master_data.delete'),('DIREKTUR','master_data.edit'),('DIREKTUR','master_data.view'),('DIREKTUR','progress.view'),('DIREKTUR','projects.view'),('DIREKTUR','rap.view'),('DIREKTUR','users.view'),
  ('KEUANGAN','dashboard.view'),('KEUANGAN','finance.add'),('KEUANGAN','finance.delete'),('KEUANGAN','finance.edit'),('KEUANGAN','finance.view'),('KEUANGAN','laporan.view'),('KEUANGAN','master_data.view'),('KEUANGAN','projects.view'),('KEUANGAN','rap.view'),
  ('MARKETING','dashboard.view'),('MARKETING','master_data.view'),('MARKETING','projects.add'),('MARKETING','projects.edit'),('MARKETING','projects.view'),
  ('PELAKSANA','dashboard.view'),('PELAKSANA','master_data.view'),('PELAKSANA','progress.add'),('PELAKSANA','progress.delete'),('PELAKSANA','progress.edit'),('PELAKSANA','progress.view'),('PELAKSANA','projects.view')
)
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from mapping m
join public.roles r on r.name=m.role_name
join public.permissions p on p.name=m.permission_name
on conflict (role_id,permission_id) do nothing;
